development:
  adapter: mysql
  database: brianwat_firstdevelopment
  username: brianwat_rails
  password: W1nt3rmuTe
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: brianwat_firsttest
  username: brianwat_rails
  password: W1nt3rmuTe
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: brianwat_firstproduction
  username: brianwat_rails
  password: W1nt3rmuTe
  socket: /tmp/mysql.sock
